const express = require('express')
const router = express.Router()
const userAuth = require('../middleWares/auth')
const userController  = require('../controllers/userController')
router.post('/userRegister',userController.userRegister)
router.post('/userSignin',userController.userSignin)
router.post('/addDomain',userController.addDomain)
router.get('/getDomains',userAuth,userController.getDomains)
router.post('/getDns',userAuth,userController.getDns)
router.post('/addRecords',userAuth,userController.addRecord)
router.post('/editRecords',userAuth,userController.editRecord)
router.post('/deleteRecord',userAuth,userController.deleteRecord)
router.post('/deleteDomain',userAuth,userController.deleteDomain)
module.exports = router